#!/usr/bin/env bash
# Traps signals and creates a file containing its pid
echo $$ | sudo tee -a /var/run/myscript.pid > /dev/null
trap 'echo I hate the kill command ; sudo rm /var/run/myscript.pid ; exit' TERM
trap 'echo Y U no love me?!' INT
trap 'sudo rm /var/run/myscript.pid ; exit' QUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
